### ISSUE TITLE
Users should be notified when a "Delete Transaction" is successful, as it doesn't update until they back out of the category page

### ISSUE THREAD

**Issue by gregsakai** [BudgetTrackerOrg/BudgetTracker#127]

**Comment by gregsakai** [comment]
Same with editing transactions

**Comment by PashanIrani** [comment]
this has todo with filtering when the state is updated. Look at 'filterChangedCallback' in homescreen.js. That method needs to be called whenever the state is changed. As that is what happens when you edit/delete a transaction

**Comment by gregsakai** [comment]
I will look into it, thanks!
